project:
  type: website
  output-dir: docs

website:
  title: "topr examples"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - manhattan.qmd
      - regionplot.qmd
      - locuszoom.qmd
      - effectplot.qmd
  sidebar:
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



